export const namaMk = [
  "kuliah kerja mahasiswa",
  "kuliah kerja mahasiswa (kkm)",
  "kuliah kerja nyata",
  "kuliah kerja nyata ",
  "kknkuliah kerja nyata",
  "kuliah kerja nyata (kkn)",
  "kkn (kuliah kerja nyata)",
  "kkm (kuliah kerjanyata mahasiswa)",
  "kuliah kerja nyata kkn",
  "kuliah kerja mahasiswa kkm",
  "kkm",
  "kkn",
  "field studykuliah kerja nyata",
  "kuliah kerja nyata mahasiswa",
  "kuliah kerja-nyata mahasiswa (kkm)",
  "kuliah kerjanyata mahasiswa",
];

export const cariKata = [
  "kuliah kerja",
  "kerja nyata",
  "kkm",
  "kkn",
  "field",
  "kerja mahasiswa",
  "nyata mahasiswa",
  "kerjanyata",
  "kerja-nyata",
];
